services:
  llmigrator-db-api:
    container_name: llmigrator-db-api
    image: llmigrator-db-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    restart: unless-stopped
